MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/coco/models/R-50.pth"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_MASK_HEAD:
    PREDICTOR: "MaskRCNNC4Predictor"
  SHARE_FEATURES_DURING_TRAINING: True
  MASK_ON: True
DATALOADER:
  IMAGES_PER_BATCH_TRAIN: 1
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
